POST http://localhost:3000/register/
Content-Type: application/json 

{
  "number": "9618701926",
  "username": "adam_richh",
  "password": "rinxkjsdhkj",
}

###
POST http://localhost:3000/login/ 
Content-Type: application/json

{
    "number": "9999999999",
    "password": "ri",
}